app/app.py
from flask import Flask
from dotenv import load_dotenv
import os

from utils.extensions import mysql, discord
from routes import register_routes

def create_app():
    app = Flask(__name__)
    load_dotenv()

    app.config["SECRET_KEY"] = os.getenv("APP_SECRET_KEY")

    app.config["MYSQL_USER"] = os.getenv("MYSQL_USER")
    app.config["MYSQL_PASSWORD"] = os.getenv("MYSQL_USER_PASSWORD")
    app.config["MYSQL_DB"] = os.getenv("MYSQL_DATABASE")
    app.config["MYSQL_HOST"] = os.getenv("MYSQL_HOST")

    app.config["DISCORD_CLIENT_ID"] = os.getenv("DISCORD_CLIENT_ID")
    app.config["DISCORD_CLIENT_SECRET"] = os.getenv("DISCORD_CLIENT_SECRET")
    app.config["DISCORD_REDIRECT_URI"] = os.getenv("DISCORD_REDIRECT_URL")
    os.environ["OAUTHLIB_INSECURE_TRANSPORT"] = "true" 

    mysql.init_app(app)
    discord.init_app(app)
    app.discord = discord

    register_routes(app, discord)

    return app

if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)

app/routes/__init__.py
from .main import main
from .auth import auth
from .api import api

def register_routes(app, discord):
    app.discord = discord

    app.register_blueprint(main)
    app.register_blueprint(auth)
    app.register_blueprint(api)

app/routes/api.py
from flask import Blueprint, request, jsonify
import requests, json

api = Blueprint("api", __name__)

@api.route("/api/generate", methods=["POST"])
def chat():
    data = request.get_json()
    query = {
        'model': 'BaseModel',
        'messages': data["messages"]
    }

    r = requests.post(
        'http://127.0.0.1:8080/chat/completions',
        data=json.dumps(query),
        headers={'Content-Type': 'application/json'}
    )
    r = json.loads(r.content)
    
    data_to_return = {
        'created': r["created"],
        'usage': r["usage"],
        'message': r["choices"][0]["message"]["content"]
    }
    return jsonify(data_to_return)

app/routes/auth.py
from flask import Blueprint, session, redirect, url_for, render_template, current_app
from flask_discord import Unauthorized

from utils.sql import store_discord_tokens
from utils.auth_utils import requires_whitelisted

auth = Blueprint("auth", __name__)

@auth.route("/login")
def login():
    return current_app.discord.create_session()

@auth.route("/callback")
def callback():
    current_app.discord.callback()

    user = current_app.discord.fetch_user()
    discord_tokens = session.get('DISCORD_OAUTH2_TOKEN')

    session["user_id"] = user.id
    session["discord_username"] = user.username
    session["logged_in"] = True

    store_discord_tokens(
        user.id,
        user.username,
        user.avatar_url,
        discord_tokens["access_token"],
        discord_tokens["refresh_token"],
        discord_tokens["expires_in"]
    )

    return redirect(url_for("auth.query"))


@auth.route("/chat")
@requires_whitelisted
def query():
    return render_template("query.html")


@auth.errorhandler(Unauthorized)
def redirect_unauthorized(e):
    return redirect(url_for("main.index"))

app/routes/main.py
from flask import Blueprint, render_template

main = Blueprint("main", __name__)

@main.route("/")
def index():
    return render_template("index.html")

app/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>RadioGPT</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/index.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/navbar.css') }}" />
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <link rel="icon" type="image/x-icon" href="/static/images/logo-outline.png">
        <div class="navbar">
            <a class="navbar-logo" href="{{ url_for('main.index') }}"><img src="/static/images/logo-outline.png"></a>
            <div class="navbar-options">
                <a href="{{ url_for('auth.login') }}" class="navbar-option-link">Login</a>
            </div>
        </div>
    </head>
    <body>
    </body>

</html>

app/templates/query.html
<!DOCTYPE html>
<html>
    <head>
        <title>RadioGPT</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/query.css') }}" />
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/navbar.css') }}" />
        <script type= "text/javascript" src="{{ url_for('static',filename='javascript/autoscroll.js') }}"></script>
        <script type= "text/javascript" src="{{ url_for('static',filename='javascript/queries.js') }}"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
        <link rel="icon" type="image/x-icon" href="/static/images/logo-outline.png">
        <div class="navbar">
            <a class="navbar-logo" href="{{ url_for('main.index') }}"><img src="/static/images/logo-outline.png"></a>
        </div>
    </head>
    <body>
        <h1 id='welcome-text' class="intro-name">RadioGPT</h1>
        <form id="query">
            <div id="query-location" class="query-location">
                <textarea maxlength="2056" id="user-query-input" placeholder="Ask me anything..."></textarea>
            </div>
        </form>
        <div id="conversation-area" class="conversation">
        </div>
    </body>

</html>